button:
  include: false
  theme:
    prototype: false
card:
  include: false
  theme:
    prototype: false
checkbox:
  include: false
  theme:
    prototype: false
divider:
  include: false
  theme:
    prototype: false
icons:
  include: false
  theme:
    prototype: false
image:
  include: false
  theme:
    prototype: false
input:
  include: false
  theme:
    prototype: false
label:
  include: false
  theme:
    prototype: false
loader:
  include: false
  theme:
    prototype: false
media:
  include: false
  theme:
    prototype: false
progress:
  include: false
  theme:
    prototype: false
reveal:
  include: false
  theme:
    prototype: false
segment:
  include: false
  theme:
    prototype: false
step:
  include: false
  theme:
    prototype: false
dropdown:
  include: false
  theme:
    prototype: false
form:
  include: false
  theme:
    prototype: false
menu:
  include: false
  theme:
    prototype: false
message:
  include: false
  theme:
    prototype: false
modal:
  include: false
  theme:
    prototype: false
nag:
  include: false
  theme:
    prototype: false
popup:
  include: false
  theme:
    prototype: false
search:
  include: false
  theme:
    prototype: false
sidebar:
  include: false
  theme:
    prototype: false
accordion:
  include: false
  theme:
    prototype: false
grid:
  include: false
  theme:
    prototype: false
tab:
  include: false
  theme:
    prototype: false
table:
  include: false
  theme:
    prototype: false
layout:
  display:
    include: false
    spacing: false
  flexbox:
    include: false
mediaquery:
  palm:
    include: false
    widths: false
    layout: false
  lap:
    include: false
    widths: false
    layout: false
  lap-and-up:
    include: false
    widths: false
    layout: false
  portable:
    include: false
    widths: false
    layout: false
  desk:
    include: false
    widths: false
    layout: false
  desk-wide:
    include: false
    widths: false
    layout: false
  under-desk-wide:
    include: false
    widths: false
    layout: false
